# Generated by Django 4.2.7 on 2024-01-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='dloc',
            new_name='dlocation',
        ),
    ]
